### ISSUE TITLE
raise when checking activerecord version

### ISSUE THREAD

**Issue by sohorx** [sinatra-activerecord/sinatra-activerecord#110]
in a bundle --standalone environment, activerecord doesn't exist in Gem.loaded_spec hence raise while trying to access it.

**Comment by cupnoodle** [comment]
Ah I see, would you mind to elaborate more on your use case here? I am trying to understand what you are trying to achieve in `bundle --standalone` environment, as this won't load active record, the gem might not function at all even after the `Gem.loaded_spec` line is removed.

**Comment by sohorx** [comment]
I'm trying build a sinatra app which does not require bundle to work.  
For doing so I'm running 
```sh
bundle install --no-cache --standalone --binstubs=$(DSTDIR)/bin --with=$(APP_ENV) --path=$(DSTDIR)
```
And so running my app in rake with something like this:
```sh
$(DSTDIR)/bin/puma -C $(DSTDIR)/config/puma.rb $(DSTDIR)/config.ru
```
everything seems to work except when my app require sinatra-activerecord (which raise when trying to use Gem.loaded_spec).
replacing the line in `lib/sinatra/activerecord.rb+10`: 
```ruby
require 'active_record/database_configurations/connection_url_resolver' if Gem.loaded_specs["activerecord"].version >= Gem::Version.create('6.1')
```
with
```ruby
require 'active_record/database_configurations/connection_url_resolver' if ActiveRecord.version >= Gem::Version.create('6.1')
```
seems to fix the issue.

**Comment by cupnoodle** [comment]
Fixed in https://github.com/sinatra-activerecord/sinatra-activerecord/pull/109
