### ISSUE TITLE
`LoadError: cannot load such file -- sinatra/activerecord/rake/activerecord_7`

### ISSUE THREAD

**Issue by POPPIN-FUMI** [sinatra-activerecord/sinatra-activerecord#120]
It gets error with activesupport 7
```
gem "activesupport", "7.0.0"
```

```
rake db:migrate
rake aborted!
LoadError: cannot load such file -- sinatra/activerecord/rake/activerecord_7
<internal:/home/fudo/.rbenv/versions/3.0.3/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:148:in `require'
<internal:/home/fudo/.rbenv/versions/3.0.3/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:148:in `require'
<internal:/home/fudo/.rbenv/versions/3.0.3/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:96:in `require'
<internal:/home/fudo/.rbenv/versions/3.0.3/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:96:in `require'
/home/fumi/dev/souls-app/apps/api/Rakefile:3:in `<top (required)>'
(See full trace by running task with --trace)
```

Rakefile LINE 3
```
require "sinatra/activerecord/rake"
```

**Comment by lxmrc** [comment]
Having this issue as well.

**Comment by lxmrc** [comment]
Using Active Record 6 for now: `gem 'activerecord', '~> 6.0'`

**Comment by lxmrc** [comment]
https://stackoverflow.com/questions/30656858/undefined-method-namespace-for-mainobject-nomethoderror-active-record-r

**Comment by cupnoodle** [comment]
Thanks for reporting this, it was because there is a new major release of ActiveRecord (7), and the gem haven't add the relevant file for it, I will look into it soon.

https://github.com/sinatra-activerecord/sinatra-activerecord/blob/80e833b31f93eb4d893f0e522e2670b94d583097/lib/sinatra/activerecord/rake.rb#L2

**Comment by cupnoodle** [comment]
Hi @POPPIN-FUMI  and @lxmrc , I have just added support for ActiveRecord 7 in the latest version of this gem (2.0.25), https://rubygems.org/gems/sinatra-activerecord/versions/2.0.25 .

Would you mind updating the gem to the latest version and see if it works?

**Comment by POPPIN-FUMI** [comment]
@cupnoodle Thank you for your rapid updates. I tried it and it works now 🎊
