### ISSUE TITLE
UnknownAttribute Error for ActiveRecord 6.1.6.1

### ISSUE THREAD

**Issue by eirvandelden** [sinatra-activerecord/sinatra-activerecord#124]
Hi 👋

I have a small, single file, Sinatra app with 1 model `NfcTag`, with 2 attributes `guid` and `number`. 
After following the install guide, creating a migration and migrating my sqlite3 database, whenever I save/create my `NfcTag` object, ActiveRecord raises a UnknownAttribute Error. 

The weird thing is; when I use a debugger, I can see that the NfcTag class has both guid and number defined. Yet when saving, it suddenly forgets that they are there.

For clarity, here is a gist with my exact setup/files: https://gist.github.com/eirvandelden/172548c72aff03181418c2c04516ebd5

I'm not yet sure if this is a bug in sinatra-activerecord, some incompatibility with ActiveRecord or a bug in my setup.

**Comment by cupnoodle** [comment]
Just a hunch, does the .sqlite3 file has the `guid` and `number` column?

**Comment by eirvandelden** [comment]
Yes, they are present:
<img width="780" alt="Schermafbeelding 2022-09-04 om 20 22 03" src="https://user-images.githubusercontent.com/6593005/188327987-65900b1e-7960-497e-89e9-e0d802500449.png">
