### ISSUE TITLE
Possible Conflict with other Rake tasks

### ISSUE THREAD

**Issue by stats** [sinatra-activerecord/sinatra-activerecord#38]
By requiring the application to be loaded in the rake file, as in the second line of

```
require "sinatra/activerecord/rake"
require "./app"
```

This can cause issues with other tasks/processes which would require the application to be loaded following some configuration. An example of this is **SimpleCov** which requires the application to be loaded following its initialization. 

Is there a reason that the app is being loaded in the root rake task instead of being loader further down the chain, when _rake db:migrate_ is actually called for example?

**Comment by janko-m** [comment]
@stats Your way is now enocouraged in the readme, and I also fixed the `db:seed` task in the new version, because it wasn't requiring `db:load_config`.
