### ISSUE TITLE
LoadError: cannot load such file -- active_record/railties/databases.rake

### ISSUE THREAD

**Issue by reicheltd** [sinatra-activerecord/sinatra-activerecord#40]
When I `require 'sinatra/activerecord/rake'`in my Rakefile I get this error

log: https://gist.github.com/anonymous/159f183fb6f46e710379

**Comment by pineapplehannah** [comment]
Hi there, I'm using <code>bundle exec rake:db migrate</code> which executes fine in my console. However, it hasn't updated my schema.db file.

This is the console output with --trace:
<pre>** Invoke db:migrate (first_time)
** Invoke db:environment (first_time)
** Execute db:environment
** Invoke db:load_config (first_time)
** Execute db:load_config
** Execute db:migrate
== 20150207193544 CreateCustomers: migrating ==================================
-- create_table(:customers)
   -> 0.0010s
== 20150207193544 CreateCustomers: migrated (0.0060s) =========================

== 20150207193810 CreatePackages: migrating ===================================
== 20150207193810 CreatePackages: migrated (0.0000s) ==========================

== 20150207193857 CreateOrders: migrating =====================================
== 20150207193857 CreateOrders: migrated (0.0000s) ============================

** Invoke db:_dump (first_time)
** Execute db:_dump
** Invoke db:schema:dump (first_time)
** Invoke db:environment
** Invoke db:load_config
** Execute db:schema:dump</pre>

However, my schema.db file only contains the Customers table:
<pre># db/schema.db
ActiveRecord::Schema.define(version: 20150207193857) do

  create_table "customers", force: :cascade do |t|
    t.string "email_address"
    t.string "first_name"
    t.string "last_name"
    t.string "shipping_address"
  end

end
</pre>

I've tried running <code> rake db:migrate</code> a few times and it still hasn't updated the schema.db file.
Is there a step I'm missing? I would appreciate any feedback at all RE this problem!

**Comment by janko-m** [comment]
When you run `rake db:schema:dump`, does it update your schema appropriately?

**Comment by pineapplehannah** [comment]
Hi Janko,

Thanks for your reply. My db/schema.db file is still the same as above. However, when I check the file properties, it shows that it was modified afterI ran <code>rake db:schema:dump</code>

<pre>
C:\Sites\PetFoodMonthly>bundle exec rake db:schema:dump --trace
** Invoke db:schema:dump (first_time)
** Invoke db:environment (first_time)
** Execute db:environment
** Invoke db:load_config (first_time)
** Execute db:load_config
** Execute db:schema:dump
</pre>

**Comment by janko-m** [comment]
That's really weird. So, if you run `db:migrate`, it doesn't update db/schema.rb, even though Rake's trace says that it ran `db:schema:dump`. But if you run `db:schema:dump` directly, then db/schema.rb is updated.

It caught my eye on your migration output that both `CreatePackages` and `CreateOrders` migrations took 0 seconds to execute. Is it possible that you left them empty?

**Comment by pineapplehannah** [comment]
Below is the content of my files in db/migrate/

<pre><strong># db/migrate/20150207193544_create_customers.rb</strong>
<code>class CreateCustomers &lt; ActiveRecord::Migration
  def change
  	create_table :customers do |t|
  		t.string :email_address
  		t.string :first_name
  		t.string :last_name
  		t.text :shipping_address

  		t.timestamp
  	end
  end
end
</code>
</pre>
<pre>
<strong># db/migrate/20150207193810_create_packages.rb</strong>
class CreatePackages &lt; ActiveRecord::Migration
  def change
  	create_table :packages do |t|
  		t.string :name
  		t.text	 :description
  		t.decimal :price, precision: 8, scale: 2
  		t.integer	:billing_frequency # 1 = Once monthly, 12 = Once yearly

  		t.timestamp
  	end
  end
end
</pre>
<pre>
<strong># db/migrate/20150207193857_create_orders.rb</strong>
class CreateOrders &lt; ActiveRecord::Migration
  def change
  	create_table :orders do |t|
  		t.integer :customer_id
  		t.string :package_name
  		t.string :payment_status
  		t.string :shipping_status

  		t.timestamp
  	end
  end
end
</pre>

Once again I ran <code>db:migrate</code> & <code>db:schema:dump</code> and the content of <strong>schema.rb</strong> is still as follows:
<pre>
<strong># db/schema.rb</strong>
ActiveRecord::Schema.define(version: 20150207193857) do

  create_table "customers", force: :cascade do |t|
    t.string "email_address"
    t.string "first_name"
    t.string "last_name"
    t.string "shipping_address"
  end

end</pre>

Notice that the version timestamp in <strong>schema.rb</strong> for <code>Schema.define</code> matches that of my CreateOrders migration. Is that normal? I really appreciate your feedback about this. It might be necessary for me to start over from scratch unless I edit it manually :-/

**Comment by janko-m** [comment]
* comment out the `create_table` statements in the last 2 migrations
* `bundle exec rake db:rollback STEP=2`
* `bundle exec rake db:migrate`

I think the following happened. You created the last 2 migrations, but forgot to add the `create_table`s, and accidentally ran the migrations (creating 2 blank migrations). I assumed it because in your logs it took 0 seconds. Then you filled them in with `create_table`s, but you have already run the migrations, so schema number was already at the last version.

**Comment by pineapplehannah** [comment]
Yes! It worked! Thank you so much for all your help!

**Comment by Euklidian-Space** [comment]
I am still getting this error.  After running bundle exec rake -T   I get 

rake console                # Start IRB with application environment loaded
rake db:create              # Creates the database from DATABASE_URL or con...
rake db:create_migration    # Create a migration (parameters: NAME, VERSION)
rake db:drop                # Drops the database from DATABASE_URL or confi...
rake db:fixtures:load       # Load fixtures into the current environment's ...
rake db:migrate             # Migrate the database (options: VERSION=x, VER...
rake db:migrate:status      # Display status of migrations
rake db:rollback            # Rolls the schema back to the previous version...
rake db:schema:cache:clear  # Clear a db/schema_cache.dump file
rake db:schema:cache:dump   # Create a db/schema_cache.dump file
rake db:schema:dump         # Create a db/schema.rb file that is portable a...
rake db:schema:load         # Load a schema.rb file into the database
rake db:seed                # Load the seed data from db/seeds.rb
rake db:setup               # Create the database, load the schema, and ini...
rake db:structure:dump      # Dump the database structure to db/structure.sql
rake db:structure:load      # Recreate the databases from the structure.sql...
rake db:version             # Retrieves the current schema version number
rake specs                  # Run the specs

dont know what all that even means.  

Now when i run rake db:create i get

rake aborted!
LoadError: cannot load such file -- active_record/railties/databases.rake
/var/lib/gems/2.2.0/gems/sinatra-activerecord-2.0.5/lib/sinatra/activerecord/rake.rb:1:in `load'
/var/lib/gems/2.2.0/gems/sinatra-activerecord-2.0.5/lib/sinatra/activerecord/rake.rb:1:in `<top (required)>'
/home/data-kid/Desktop/ruby_stuff/sinatra-mvc/Rakefile:1:in `<top (required)>'
LoadError: cannot load such file -- sinatra/activerecord/rake
/home/data-kid/Desktop/ruby_stuff/sinatra-mvc/Rakefile:1:in `<top (required)>'
(See full trace by running task with --trace)
 

Don't really know how to fix this.  Any help would be awesome

**Comment by janko-m** [comment]
You need to run "**bundle exec** rake db:migrate", then it should work.

Rake is a task runner, and imagine tasks as simple Ruby scripts that do something. The "-T" flag tells Rake just to print the list of available tasks. See documentation for ActiveRecord on better explanation of these Rake tasks.

**Comment by Euklidian-Space** [comment]
Thanks janko-m.  That worked for me.

**Comment by sixtyfive** [comment]
Just ran into this after `bundle update`. Doing `bundle exec rake` as suggested here does fix it, but I'm lazy and prefer being able to simply do `rake`. After reading through the comments in this thread, I figured I'd try

```
require 'sinatra/activerecord'
require 'sinatra/activerecord/rake'
```

at the beginning of the `Rakefile`. That works like a charm. Perhaps it could be considered to require `sinatra/activerecord` from within `sinatra/activerecord/rake`. Good night everyone!

**Comment by sg552** [comment]
just upgrade to 2.0.14 , problem solved.

**Comment by abrahamcuenca** [comment]
Thanks guys, I was trying to figure this out today and came upon this thread. Looks like bundle exec worked for me too, Since bundle exec is a Bundler command to execute a script in the context of the current bundle that may be why it works only when using `bundle exec`
