### ISSUE TITLE
Unable to set database pool variable on heroku when using database.yml

### ISSUE THREAD

**Issue by miltzi** [sinatra-activerecord/sinatra-activerecord#56]
We used to set the database pool size for our Heroku application in the database.yml file. Since upgrading to version 2.0.6 or later, this functionality has stopped working.

Version 2.0.6 introduces an order change in preference of database.yml and a database URL for configuring the database which caused our pool settings to be ignored. 

Should these two configurations be merged rather than choosing the database URL and ignoring the database.yml options if the file exists?

At the moment our only way of setting the pool size seems to be by hardcoding it onto the database URL by appending `?pool=x` which is obviously not ideal.

**Comment by jamesrwhite** [comment]
The behaviour should probably match what is stated here: http://guides.rubyonrails.org/configuring.html#connection-preference (if that isn't already the case). Is this still an issue for you?

**Comment by jayroh** [comment]
I have this issue as well. Looking at the code [here] it's either one or the other - no merging.

Has anyone implemented a solution or found another way of getting around this?

[here]: https://github.com/janko-m/sinatra-activerecord/blob/master/lib/sinatra/activerecord.rb#L19-L23

**Comment by jesseminer** [comment]
@cupnoodle This issue hasn't had any activity in years, but is it a change you'd be open to? I'm just starting to look at the relevant code.

Alternatively, or as a short term workaround, do you think it would be safe to run the following?
```
require 'sinatra/activerecord'

db_config = ActiveRecord::Base.configurations[Sinatra::Application.environment]
db_config['pool'] = ENV.fetch('DB_POOL', 5)
ActiveRecord::Base.connection_pool.disconnect!
ActiveRecord::Base.establish_connection(db_config)
```

**Comment by cupnoodle** [comment]
@jesseminer  I am no expert on database matter, but from first glance I don't think it's a good idea to disconnect and establish connection like this.

I have just look into https://guides.rubyonrails.org/configuring.html#connection-preference , seems like DATABASE_URL's variables will have precedence over database.yml if both of them are present. Currently this repo will ignore database.yml if DATABASE_URL is defined : https://github.com/sinatra-activerecord/sinatra-activerecord/blob/master/lib/sinatra/activerecord.rb#L19-L23

I will try looking into how Rails does the merging when I am free (currently quite occupied with work 😅), feel free to create PR if you feel like it !

**Comment by cupnoodle** [comment]
Resolved with this PR https://github.com/sinatra-activerecord/sinatra-activerecord/pull/103
