### ISSUE TITLE
Intructions for contributors

### ISSUE THREAD

**Issue by fabioperrella** [sinatra-activerecord/sinatra-activerecord#83]
Hi!

I've just cloned the repo and when I tried to run the spec, I've got this failure:

```
$ bundle exec rake

Set SINATRA_ACTIVESUPPORT_WARNING=false in the environment to hide this warning.
-- alias_method_chain(:migrate, :quietness)

An error occurred while loading ./spec/sinatra/activerecord/rake_spec.rb.
Failure/Error: alias_method_chain :migrate, :quietness

ActiveRecord::ConnectionNotEstablished:
  No connection pool with 'primary' found.
# ./spec/sinatra/activerecord/rake_spec.rb:10:in `<class:Migration>'
# ./spec/sinatra/activerecord/rake_spec.rb:4:in `<top (required)>'


Finished in 0.0004 seconds (files took 1.17 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples
```

It is necessary to setup something before running the specs?

If yes, it would be great to have this instruction somewhere, maybe in a file like CONTRIBUTING.md

wdyt?

**Comment by cupnoodle** [comment]
Seems like its because Rails has removed alias_method_chain method, in favor of prepend

https://github.com/rails/rails/commit/7c848e6dd493ff236d33a0410a92f4c3e5cc3c7f

**Comment by cupnoodle** [comment]
Heya @fabioperrella , I have since fixed the issue and added a Contributing guide here : https://github.com/sinatra-activerecord/sinatra-activerecord/blob/master/CONTRIBUTING.md , thanks for the suggestion!
