### ISSUE TITLE
DEPRECATION WARNING: Setting `ActiveRecord::Base.configurations` with `[]=` is deprecated.

### ISSUE THREAD

**Issue by npolevara** [sinatra-activerecord/sinatra-activerecord#89]
after connect activerecord-6.0.0

**Comment by janko** [comment]
FYI, I'm searching for a new maintainer – https://github.com/janko/sinatra-activerecord/issues/90.

**Comment by dbackeus** [comment]
@jobro (assuming you are the new maintainer) any plans to get Rails 6 compatibility going?

**Comment by samfolo** [comment]
unhelpful.

**Comment by janko** [comment]
FWIW, I reopened #90.
