### ISSUE TITLE
Maintainer wanted

### ISSUE THREAD

**Issue by janko** [sinatra-activerecord/sinatra-activerecord#90]
I'm not using Sinatra nor Active Record anymore, and already have other open source projects I'm deeply committed to, so I would like to pass sinatra-activerecord maintenance over to someone else.

Any volunteers?

**Comment by janko** [comment]
@jobro has volunteered to take over maintenance of sinatra-activerecord 🎉  Thank you @jobro 🙏

**Comment by jobro** [comment]
Happy to!

**Comment by janko** [comment]
There hasn't been any new activity since I've given @jobro push access, so I'm reopening this issue in search for another volunteer.

**Comment by cupnoodle** [comment]
Hi @janko , is this still open? I am happy to be a maintainer as I am using Sinatra and Sinatra Active Record for my own side project, and want to fix several issue like #83 and #89

Thanks for maintaining this repository!

**Comment by janko** [comment]
@cupnoodle Great! I've invited you to the organization. Please let me know your RubyGems.org email address so that I can give you gem push access.

**Comment by cupnoodle** [comment]
Thanks @janko ! My RubyGems.org email is axel@fluffy.es

**Comment by cupnoodle** [comment]
Let me know after you have given the gem push access.

I just found out that the version pushed to RubyGems doesn't match the version in Github (2.0.14 on RubyGems on September 2019, but 2.0.13 on Github)  , sorry for the double bump 😅

**Comment by janko** [comment]
Done, you should now have gem push access ✅ Thank you for jumping in!
